name: FantasticMrFix
favicon: null
layout_spectrum: 0.9552618069574237
typography_spectrum: 0.6002992747817189
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#5e5e5e'
    - '#da7cd5'
    - '#50b051'
  brandStrength: 0.6000591642223299
  lightness: 0.10054963501170278
  saturation: 0.904199015814811
  rhythmicContrast: 0.5744946103077382
purpose: []
