name: FantasticMrFix
favicon: null
layout_spectrum: 0.9552618069574237
typography_spectrum: 0.6002992747817189
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6000591642223299
  lightness: 0.10054963501170278
  saturation: 0.904199015814811
  rhythmicContrast: 0.5744946103077382
purpose: []
